### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by trypsynth** [JonathanRaiman/epub_conversion#8]
[Hi @JonathanRaiman,
What is the status of this project? I have a project that it would be quite useful for, but it hasn't been updated in a few years and might not work on more modern Python.

**Comment by JonathanRaiman** [comment]
Haven't updated in a while - it's possible that some of the dependencies have changed, but I was using this with Python 3 originally. If you run into any issues would be happy to accept PRs :)

**Comment by trypsynth** [comment]
Gotcha :) thanks
